### PR TITLE
added confirm button to modal which shows when screen size is less th…

### LINKED ISSUE #1: Enter name without button on mobile isn't intuitive
It makes sense on the website to enter your name and hit enter, but it's a little unorthodox on mobile where you have to hit return.
image

### PR DESCRIPTION
**Pull request by tonesija**
…an 800px, resolves #1

### CODE REVIEW

**Comment by LukeGarrigan** [comment]
Hi, thank you for your contribution, what you have is broadly correct!

Rather than the confirm button underneath, it would be better if the submit/enter was apart of the input itself.

Here's an example of what I mean [http://jsfiddle.net/s5GVh/](http://jsfiddle.net/s5GVh/)

**Comment by tonesija** [comment]
Okay, what would you like to do with css that can be reused? One solution would be to place it in App.vue to make it global.

**Comment by LukeGarrigan** [comment]
I think it'll be fine in the modal at the moment - when we're in a scenario where we require it again, we'll make the move.

**Comment by LukeGarrigan** [comment]
I've updated master so we have a new button next to the input, not 100% sold on it but it'll do for now. All this needs is merging and we're good to go.

**Pull request closed without merging**
