### PR TITLE
feat: Add T-Shirt sizing as one of the voting options

### LINKED ISSUE #11: Add options for different voting systems
Not everybody uses the Fibonacci sequence to do their estimating, here are some other examples we should add:

T-shirts: XXS, XS, S, M, L, XL, XL, ?
Powers of 2: 0, 1, 2, 4, 8, 16, 32, 64, ?

There's also the modified Fibonacci, but I'm not too bothered about that one.

### PR DESCRIPTION
**Pull request by Ruandv**
# Feature : New sizing options

## This will close #11 

- Added a new config option to the top left of the screen: 
image

- Clicking that button will open a Modal that retrieves the gameTypes from the "server": 
image

### CODE REVIEW

**Comment by Ruandv** [comment]
@LukeGarrigan @lalondeph I have created a draft PR for the voting changes (branched off PR #45) 
Let me know what you think.

**Comment by LukeGarrigan** [comment]
Cheers. Could you separate the localisation stuff so it's not apart of this PR please

**Comment by Ruandv** [comment]
Done. I will close this PR and create a new one 👍

**Comment by Ruandv** [comment]
Replaced by #47 to split between lokalization ( #44 ) and Sizing options ( #11 ).

**Pull request closed without merging**
